### ISSUE TITLE
is it possible to create png output instead of svg?

### ISSUE THREAD

**Issue by cksidharthan** [nikolaydubina/go-cover-treemap#26]
I am using this tool in my project hosted in Azure Devops. But the Web preview of the readme in AZDO is not able to show svg. It would be awesome if the tool has an option to output png files

**Comment by nikolaydubina** [comment]
interesting. png and raster graphics is supported in go.

but these days I think it is better to use other tool to render SVG into png. perhaps either in pipeline or as a second tool on top of this one.

I would keep this tool to generate SVG for now. If more people need, then will add png!

**Comment by cksidharthan** [comment]
Yup. I agree 👍🏻
