### ISSUE TITLE
explain a bit more about the statements version

### ISSUE THREAD

**Issue by MarcelXia** [nikolaydubina/go-cover-treemap#3]
Do I need to do it differently in order to get the statement heatmap?

(BTW: Love this tool)

**Comment by nikolaydubina** [comment]
Thank you! 

To your question, in short, no. 

Statements mode is default in this tool. What this means is that size of each box is proportional to number of statements. Now, alternative mode is counting files in package (it would set each file to size 1). tbh, you may not want to use that. Default mode, statements is proven to be more useful!

And in `go test -v -coverprofile=coverage.txt -covermode=atomic` has atomic, set, and count modes. All these modes produce statements coverage. So any coverprofile should work! From official docs:
> -  set: did each statement run?
> -  count: how many times did each statement run?
> -  atomic: like count, but counts precisely in parallel programs

https://go.dev/blog/cover
