### ISSUE TITLE
maps for colour blind

### ISSUE THREAD

**Issue by Br3nda** [nikolaydubina/go-cover-treemap#32]
One member of my team is colour blind so i feel pretty bad showing off these maps in our CI output

Is there something i can do to get output in colours that are not red/green?

**Comment by nikolaydubina** [comment]
Hey, of course! I dealt with accessibility very long time ago back at Meta 😅

could you suggest color scheme (or style, dots, patterns, etc.) that will work and look good for them?

**Comment by Br3nda** [comment]
I've made some red/blue maps and posted them to our Slack for feedback, but our colour-blind team members won't know what info they're missing in the first place.
