### ISSUE TITLE
Percent Coverage

### ISSUE THREAD

**Issue by artemovechkin** [nikolaydubina/go-cover-treemap#73]
Hi, the team and I thought it would be great to see the percentage of coverage when visualizing

I have implemented this, but there is a question of how relevant it would be to see? And if it is relevant, in which of the projects should I open a pull request?
treemap or in this go-cover-treemap? 

I think that according to the logic of the projects, the launch flag and the call should occur in go-cover-treemap, and the implementation in treemap? What do you think?
If we come to a common understanding, I will be glad to participate

![image](https://github.com/user-attachments/assets/ca9d018f-ef13-4462-81ee-dade69844cdb)

**Comment by nikolaydubina** [comment]
cool! let's merge it.

this is definitely `go-cover-treemap`. `treemap` package is more fundamental. percentage is very much user/consumer level.

implementation likely in `go-cover-treemap`.

raise a PR. let's check if this looks good. may be you are right, if lots needs to be changed in the `treemap` level, then maybe need to update it instead.

check https://github.com/nikolaydubina/go-binsize-treemap. it has something similar, but absolute values.
